# Generated by Django 2.1.7 on 2019-04-03 01:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('StepModel', '0002_auto_20190402_2114'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stepmodel',
            old_name='Step_text',
            new_name='Steps',
        ),
    ]
