# Generated by Django 2.1.7 on 2019-04-03 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StepModel', '0003_auto_20190402_2151'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stepmodel',
            name='Steps',
        ),
        migrations.AddField(
            model_name='stepmodel',
            name='step_text',
            field=models.TextField(blank=True, max_length=500),
        ),
    ]
