# Generated by Django 2.1.7 on 2019-04-04 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StepModel', '0006_stepmodel_srecipe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stepmodel',
            name='step_text',
            field=models.TextField(default='', max_length=255),
        ),
    ]
