# Generated by Django 2.1.7 on 2019-04-03 02:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RecipeModel', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipemodel',
            old_name='name',
            new_name='Name',
        ),
    ]
