# Generated by Django 2.1.7 on 2019-04-03 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IngredientModel', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredientmodel',
            name='Ingredient',
        ),
        migrations.AddField(
            model_name='ingredientmodel',
            name='text',
            field=models.CharField(default='', max_length=255),
        ),
    ]
