# Generated by Django 2.1.7 on 2019-04-04 02:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('RecipeModel', '0003_recipemodel_author'),
        ('IngredientModel', '0002_auto_20190402_2214'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredientmodel',
            name='IRecipe',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='RecipeModel.RecipeModel'),
        ),
    ]
